{
 "title": "Lifx Wifi",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "group",
    "query": {
     "query": "label_values(lifx_bulb_wifi_signal,group)"
    }
   }
  ]
 },
 "panels": [
  { "title": "$group", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "group" },
  {
   "title": "Wifi Signal",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "abs(floor(10* log10(lifx_bulb_wifi_signal{group=\"$group\"}) +0.5))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Wifi Signal",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "abs(floor(10* log10(lifx_bulb_wifi_signal{group=\"$group\"}) +0.5))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Wifi Tx",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "lifx_bulb_wifi_tx{group=\"$group\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Wifi Rx",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "lifx_bulb_wifi_rx{group=\"$group\"}",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}